package com.mukarram.businessmanagementapp.DatabaseApp.DataClasses

import androidx.annotation.NonNull
import androidx.room.*
import com.mukarram.businessmanagementapp.DatabaseApp.ConvertersClass.Converter

@Entity(
    tableName = "productBill",
    foreignKeys = [
        ForeignKey(entity = Bill::class,
            parentColumns = ["billId"],
            childColumns = ["billId"],
            onDelete = ForeignKey.CASCADE),
    ]
)
data class ProductBill(
    @PrimaryKey(autoGenerate = true) val id: Long = 0L, // An autogenerated ID for each product entry
    @NonNull val billId: Long,
    val totalBill: Double,
    @TypeConverters(Converter::class)
    val productEntries: List<ProductEntry>,

)


